apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app-ingress
    namespace: default
    annotations:
        haproxy.org/ingress.class: haproxy
spec:
    ingressClassName: haproxy
    rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: webservice
              port:
                number: 80